export const SAMPLE_HTML = [
  '<p>아래 샘플은 <strong>tables</strong> 확장을 시연합니다. 3x3 표에 2-3행의 첫 번째 셀이 <code>rowspan=2</code>로 병합되어 있습니다.</p>',
  '<table class="rte-table">',
  '<thead>',
  '<tr><th><p>항목</p></th><th><p>값</p></th><th><p>비고</p></th></tr>',
  '</thead>',
  '<tbody>',
  '<tr>',
  '<td rowspan="2"><p>공용</p></td>',
  '<td><p>A1</p></td>',
  '<td><p>병합된 셀</p></td>',
  '</tr>',
  '<tr>',
  '<td><p>A2</p></td>',
  '<td><p>의 두 번째 행</p></td>',
  '</tr>',
  '<tr>',
  '<td><p>단일</p></td>',
  '<td><p>B1</p></td>',
  '<td><p>— </p></td>',
  '</tr>',
  '</tbody>',
  '</table>',
  '<p>편집: 셀 이동은 <kbd>Tab</kbd> / <kbd>Shift+Tab</kbd>. 행/열 추가·셀 병합·분리는 위쪽 "표 명령 toolbar" 버튼으로. 두 개 이상 셀 병합은 드래그로 셀 영역을 선택한 뒤 "셀 병합" 클릭.</p>',
].join('')
