export const SAMPLE_HTML = [
  '<h1>교안 작성 가이드</h1>',
  '<p>아래 샘플은 <strong>headings · lists · links</strong> 확장을 시연합니다.</p>',
  '<h2>학습 목표</h2>',
  '<ul>',
  '<li>헤딩 계층 구조 확인',
  '<ul>',
  '<li>H1 → H2 → H3 중첩 표기</li>',
  '<li>중첩 리스트 렌더링</li>',
  '</ul>',
  '</li>',
  '<li>순서 리스트 사용</li>',
  '<li>링크 자동 감지 (autolink)</li>',
  '</ul>',
  '<h3>실습 순서</h3>',
  '<ol>',
  '<li>헤딩 단축키 연습 (<code>Ctrl+Alt+1~3</code>)</li>',
  '<li>리스트 항목 추가</li>',
  '<li>링크 입력: 공식 문서는 <a href="https://tiptap.dev">TipTap</a>에서 확인할 수 있습니다.</li>',
  '</ol>',
  '<p>아래 빈 문단에 <code>https://example.com</code>을 직접 타이핑해 autolink 동작을 확인해보세요.</p>',
  '<p></p>',
].join('')
